### ISSUE TITLE
Więcej danych dla lepszego śledzenia przesyłek

### ISSUE THREAD

**Issue by kutzowsky** [kutzowsky/BlabPrezent#10]
1. Zbierać od userów numery telefonów w celu podawania ich kurierom.
2. Pobierać przy potwierdzeniu wysłania numer przesyłki i/lub realizującego przesyłkę i/lub link jej śledzenia.

Zastanowić się nad tym jak to sensownie i bezpiecznie przechowywać oraz walidować,

**Comment by kocimokiem** [comment]
wymóc regulaminem.

**Comment by kucyk** [comment]
Po namyśle, zastanawiam się nad:
1. Jeśli chcesz lepszej gwarancji i żeby kurier dzwonił - podajesz numer. Jeśli nie chcesz podać - to liczysz się z mniejszą "kontrolą" nad przesyłką.
2. Obowiązek podania linku śledzenia przesyłki przy potwierdzeniu wysłania botu.

**Comment by kutzowsky** [comment]
1. Jako tako działa. 
2. Ficzer na kiedyś.

Można też dopisać sugestię wysyłania przesyłek czymś, co umożliwia w miarę dobry tracking.

**Comment by kutzowsky** [comment]
1 się sprawdziło, na 2 jest osobne issue, więc to można zamknąć.
