### ISSUE TITLE
Informacja o wysłaniu/otrzymaniu prezentu

### ISSUE THREAD

**Issue by kutzowsky** [kutzowsky/BlabPrezent#5]
Był taki pomysł na ficzer żeby po tym jak ktoś potwierdzi wysłanie/otrzymanie prezentu, druga strona (odpowiednio obdarowywany i obdarywowu... ten drugi... dający prezent) miała informację w postaci wiadomości prywatnej, że ma oczekiwać na przesyłkę/przesyłka szczęśliwie dotarła. 

Do rozważenia jak to zrobić, bo to zmieniałoby obecną logikę w stopniu dość znacznym.

**Comment by kucyk** [comment]
Istnieje ryzyko deanonimizacji przez korelację.
**Scenariusz:**
Ktoś wysłał prezent, potwierdził i zaraz się pochwalił publicznie. Zobaczyć to może osoba, do której prezent został wysłany i domyślić się od kogo. 

Ficzer ciekawy, tylko przez to nie wiem, czy go implementować.

**Comment by kucyk** [comment]
Wymagane jeśli #10 zostanie zaimplementowane. Adresat dostanie info o wysłaniu z linkiem śledzenia.

**Comment by kutzowsky** [comment]
#10 nie jest wymagane w pierwszej wersji. Potwierdzenie może być tak o - bez linka.
